version: "3.8"

services:
  ubos-develop:
    container_name: ubos-develop
    image: ubos/ubos-develop-${CHANNEL:-yellow}:latest
    working_dir: /home/ubosdev
    privileged: true
    volumes:
      - ./ubos-develop-home-ubosdev:/home/ubosdev

  ubos-target:
    container_name: ubos-target
    image: ubos/ubos-target-${CHANNEL:-yellow}:latest
    working_dir: /var/shepherd
    ports:
      - 8080:80
      - 8443:443
    privileged: true
    volumes:
     - ./ubos-target-home-shepherd:/var/shepherd
